version: '3.7'

services:
    my-backend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./src:/myfolder/src
        env_file:
            - .env
        ports:
            - 4000:4000
        environment:
            - TZ=Asia/Seoul

    my-database:
        image: mysql:latest
        env_file:
            - .env.db
        ports:
            - 3306:3306
        environment:
            - TZ=Asia/Seoul

    redis:
        image: redis:latest
        ports:
            - 6379:6379

    # my-frontend:
    #     build:
    #         context: ../frontend
    #         dockerfile: Dockerfile.front
    #     volumes:
    #         - ../frontend/src:/myfolder/src
    #         - ../frontend/public:/myfolder/public
    #     env_file:
    #         - .env
    #     ports:
    #         - 3000:3000

    # api-gateway:
    #     image: nginx:latest
    #     volumes:
    #         - ../api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    #     ports:
    #         - 80:80
